CREATE SEQUENCE perfil_seq INCREMENT BY 1;

CREATE SEQUENCE fornecedor_seq INCREMENT BY 1;

CREATE SEQUENCE tutorial_seq INCREMENT BY 1;

CREATE SEQUENCE venda_seq INCREMENT BY 1;

CREATE SEQUENCE usuario_seq INCREMENT BY 1;